### PR TITLE
zerocracy/farm#172 Moved ProjectFarm from farm to jstk

### PR DESCRIPTION
**Pull request by carlosmiranda**
zerocracy/farm#172 Moved ProjectFarm from https://github.com/zerocracy/farm project and renamed it to `FkFarm`.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:zerocracy/jstk#16` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @carlosmiranda, total is [+585](http://www.0crat.com/u/carlosmiranda).

**Comment by yegor256** [comment]
@carlosmiranda don't you think that it would be better to make `FkFarm` smarter, instead of creating a new class?

**Comment by carlosmiranda** [comment]
@yegor256 you're perfectly right, I removed `FkProjectFarm` and added constructors to `FkFarm` so we can accommodate the requirements.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@carlosmiranda version 0.13 is in Maven Central

**Pull request merged**
